### ISSUE TITLE
Errno 10022

### ISSUE THREAD

**Issue by brynne8** [Macronut/SNI-Mask#1]
I tried to use it on Windows, with python 2.7. But I got Errno 10022 when I access zh.wikipedia.org .

**Comment by macronut** [comment]
It's Linux only, RAW_SOCKET of Windows is receive only, can not send IP packets.
So, if you want run on Windows you must replace the RAW_SOCKET to Winpcap.

**Comment by brynne8** [comment]
Thanks.
